### ISSUE TITLE
Replacement of Url Text Entry with File Browser Selection

### ISSUE THREAD

**Issue by Madhusudansarma** [kblincoe/VisualGit_SE701_3#113]
![repositoryurlhide](https://user-images.githubusercontent.com/32195305/37860365-374a5488-2f88-11e8-868d-e00140c4e9bf.jpg)

**Current Scenario**
 In the current scenario, to clone a new repository and store the package in the desired directory, we need to enter the directory's path in the given textbox.

**Proposed change**
 Instead, we can use a file browser to select the desired directory.

**Comment by softeng-701** [comment]
This is the same as #20
