### ISSUE TITLE
Bug- Already cloned repositories using VisualGit are not accessible 

### ISSUE THREAD

**Issue by Madhusudansarma** [kblincoe/VisualGit_SE701_3#115]
Steps to Reproduce
Login into VisualGit
click on add Repository and clone any Repository
Go to add repository page and enter the path of existing repository and click open

**Expected behavior**
Open the repository for the given path

**Actual behavior**
![image](https://user-images.githubusercontent.com/32195305/37861476-839c69c2-2f9f-11e8-89b6-725e03e2b3ec.png)

Steps to resolve
investigate why the system is not able to open existing repository

**Comment by softeng-701** [comment]
@Madhusudansarma Approved

**Comment by SN4KE-EYES** [comment]
Claimed for myself
