### ISSUE TITLE
Add file explorer to opening and saving

### ISSUE THREAD

**Issue by kblincoe** [kblincoe/VisualGit_SE701_3#20]
When opening a local repository, the open button should open a file explorer, where the folder can be selected. At the moment only directories within VisualGit can be chosen. This file explorer should also be added to choosing where to save a cloned repository.

**Comment by Scoobster** [comment]
Claimed! Andrew Lyall is working on this :)

**Comment by Scoobster** [comment]
This issue was closed by Pull Request #74
