### ISSUE TITLE
Move colour settings to menu bar

### ISSUE THREAD

**Issue by kblincoe** [kblincoe/VisualGit_SE701_3#3]
Colour settings can only be changed from the top left corner of the login screen. This setting would be better placed in the menu bar for easy access anywhere in the app.

**Comment by cielluo** [comment]
Claimed!

**Comment by EmilyYVChan** [comment]
@ls-morning You can only be claiming and actively working on 1 issue at a time, but you have claimed 4 all in one go. Would you kindly delete you 'claim' comments for 3 issues? I would like to work on one of them.
