### ISSUE TITLE
Commits are allowed when there is nothing to commit

### ISSUE THREAD

**Issue by cli727** [kblincoe/VisualGit_SE701_3#51]
Currently, users are able to commit when there are no changes made at all. Pushing those commits result in:

![no-change](https://user-images.githubusercontent.com/22021804/37203295-17a442fc-23f2-11e8-81d4-16802230c2a1.JPG)

Such commits really should not be permitted as they contribute no value to the development. Therefore when there are no changes in the files, users should not be allowed to commit.

@softeng-701

**Comment by softeng-701** [comment]
Approved @cli727

**Comment by Scoobster** [comment]
Claimed Andrew Lyall

**Comment by Scoobster** [comment]
This issue was closed with Pull Request #98
