### ISSUE TITLE
Reformat Local Repository Failed Information Window

### ISSUE THREAD

**Issue by shoebilldev** [kblincoe/VisualGit_SE701_3#55]
If an incorrect path is given to Visual Git when adding a local repository an information box appears (below)

![image](https://user-images.githubusercontent.com/22441521/37259033-c1c61676-25e5-11e8-85af-8f1c6e435719.png)

The issue is that if a long path is entered, it does not wrap around and the dark text becomes almost unreadable over the black background.

The info box needs to be changed to either fit the size of the path OR the formatting inside the box needs to be changed so long path files wrap back inside the box.

This may happen in other notification windows so this issue should be extended to look for other places were paths overflow.

Edit: edited to extend to checking other info windows, not just the local repository window and changing difficulty tag to small.

Tagging @softeng-701 for approval

**Comment by softeng-701** [comment]
@tagumi This seems the same as issue #5

**Comment by shoebilldev** [comment]
@softeng-701 apologies shall I remove?
