### ISSUE TITLE
Change naming of repos cloned from GitHub

### ISSUE THREAD

**Issue by kblincoe** [kblincoe/VisualGit_SE701_3#6]
When you clone a repository from GitHub, the local folder which is created is named after the author’s name rather than the project’s name. This is especially a problem if you want to clone two repositories from the same author, as this will cause an error.

**Comment by EmilyYVChan** [comment]
@ls-morning You can only be claiming and actively working on 1 issue at a time, but you have claimed 4 all in one go. Would you kindly delete you 'claim' comments for 3 issues? I would like to work on one of them.

**Comment by EmilyYVChan** [comment]
Claimed
