### ISSUE TITLE
Password displayed in plaintext in commit tooltip

### ISSUE THREAD

**Issue by sahilcc7** [kblincoe/VisualGit_SE701_3#75]
When hovering over a commit made through VisualGit, the author field displays the password used to login to the application. 

Estimate: Small/Medium... Depending on issue #28  to find out how passwords are being stored...

![image](https://user-images.githubusercontent.com/7804304/37501507-8c338d26-2933-11e8-8b54-a2807a5a63df.png)

**Comment by sahilcc7** [comment]
@softeng-701

**Comment by softeng-701** [comment]
@sahilcc7 Approved, I'll put the small tag for now, if it takes more than a couple of hours we can change the tag, thanks
