### ISSUE TITLE
Redesign menu bar

### ISSUE THREAD

**Issue by cielluo** [kblincoe/VisualGit_SE701_3#80]
Currently VisualGit uses the default menu bar of electron. However, it is sometimes confusing to users. 
E.g. 
![menu](https://user-images.githubusercontent.com/11484369/37563424-2aaa72f0-2ae5-11e8-960d-09bf5fe695cb.jpg)
'Cut', 'Copy', 'Paste', 'Paste and Match Style', etc are unnecessary for VisualGit.
Hence, the menu bar should be redesigned to be more useful and user friendly.

@softeng-701 for review

**Comment by softeng-701** [comment]
@ls-morning Do you have a size estimate for this issue?

**Comment by cielluo** [comment]
I think small since Electron provides many build-in menu items that we can choose to redesign the menu bar.
Special requirements like Issue #3 are related to this, but they can be regarded as independent issues.
@softeng-701

**Comment by softeng-701** [comment]
@ls-morning Approved

**Comment by cielluo** [comment]
Claimed - I'll do this together with #3 since they are closely related
