### ISSUE TITLE
'Clone from Internet' with empty URL location error

### ISSUE THREAD

**Issue by cielluo** [kblincoe/VisualGit_SE701_3#81]
When cloning from Internet, if we do this

![before](https://user-images.githubusercontent.com/11484369/37563659-bd451d68-2aea-11e8-8744-43a7b6a74b3d.jpg)

Then this message would be shown

![clone-error](https://user-images.githubusercontent.com/11484369/37563672-01da7e64-2aeb-11e8-8c53-726a2dace440.jpg)

This action will freeze the GUI, and the project VisualGit itself will be cloned.
It will be more reasonable if the user get an error message and clone nothing after the action, since the URL to clone from is empty.

@softeng-701 for review

**Comment by softeng-701** [comment]
@ls-morning Do you have a size estimate for this? thanks

**Comment by cielluo** [comment]
I think medium, because investigation is necessary to find out the reason for this problem.
@softeng-701

**Comment by softeng-701** [comment]
@ls-morning Approved

**Comment by ponchotang** [comment]
Claimed.

**Comment by ponchotang** [comment]
Closing as issue is fixed.
